### ISSUE TITLE
MYSQL error occured

### ISSUE THREAD

**Issue by cwkhawand** [teodor-ionescu/000-ai-assistant#1]
Here are some Q/A the developer should add himself
Q: 000webhost rank
A: 000webhost is rated 4.9/5 by its customers.<br>According to 000webhost's directory reviews, Hostinger (the owner of 000webhost) is ranked #1 web hosting company from all web hosting users (Hostinger, 000webhost & other web hosting users).

Q: Suspended
A: That is sad to hear, please contact 000webhost's staff <a href="https://000webhost.com/forum">here</a> and explain what happened.

**Comment by teodor-ionescu** [comment]
The system now automatically escapes specific characters such as quotes and others.
